config/routes.rb
Rails.application.routes.draw do
  
  get 'comments/create'

  devise_for :users
  
  resources :topics do
    resources :posts, except: [:index] 
  end

  resources :post, only: [] do
    resources :comments, only: [:create, :destroy]
     resources :favorites, only: [:create, :destroy]

    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote

  end

  resources :users

  get 'about' => 'welcome#about'

  root to: 'welcome#index'
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  belongs_to :user
  belongs_to :topic
  has_many :votes
  has_many :favorites, dependent: :destroy


  default_scope { order('rank DESC')}
  scope :visible_to, -> (user) {user ? all: joins(:topic).where('topics.public' => true)}
  # scope :ordered_by_title, -> { order(:name) }

  validates :title, length: { minimum: 5}, presence: true
  validates :body, length: { minimum: 20}, presence: true
     validates :topic, presence: true
     validates :user, presence: true

   def up_votes
     votes.where(value: 1).count
   end

   def down_votes
     votes.where(value: -1).count
   end

   def points
      votes.sum(:value)
   end
   

   def update_rank
     
     age_in_days = (created_at - Time.new(1970,1,1)) / (60 * 60 * 24) # 1 day in seconds
     new_rank = points + age_in_days
 
     update_attribute(:rank, new_rank)
  end 


  def after_create
    user.votes.create(value: 1, post: self)
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController


  def show
    @post = Post.find(params[:id])
    @topic = Topic.find(params[:topic_id])
    @comments = @post.comments

  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
    #er wordt gecheckt of aan de voorwaarden van policy/new wordt voldaan => is user.present?
    authorize @post
  end

  #Als je geen create functie aanmaakt kun je het form niet submitten.
  def create
    #What values are permitted and required?
    @topic = Topic.find(params[:topic_id])
    @post = current_user.posts.build(params.require(:post).permit(:title, :body))
    
    @topic.posts << @post
    #wat bedoelen ze hiermee?
    # @post.topic
    authorize @post
    if @post.save
      @post.create_vote

      flash[:notice] = "Post was saved."
      #@post = post/1 bijvoorbeeld
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post"
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    # authorize @post
  end

  def update
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize @post
    #nog aanpassen aan de hand van 29.

    if @post.update_attributes(params.require(:post).permit(:title, :body, ))
      flash[:notice] = "Post was updated"
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error updating the post. Please try again."
      render :edit
    end

  end

  def destroy
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    title = @post.title



    if @post.destroy
      flash[:notice] = "\"#{title}\ was deleted"
      redirect_to @topic
    else
      flash[:error] = "Error"
      render :show
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for [topic, post] do |f| %>
  <% if post.errors.any? %>
    <div class="alert alert-danger">
      <h4>There are <%= pluralize(post.errors.count, "error") %>.</h4>
      <ul>
        <% post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_group_tag(post.errors[:title]) do %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
  <% end %>
  <%= form_group_tag(post.errors[:body]) do %>
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
  <% end %>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="media">
      <%= render partial: 'votes/voter', locals: { post: post } %>
        <div class="media-body">
          
             <h4 class="media-heading">
              <%= link_to (markdown post.title), [post.topic, post] %>
             </h4>

             <small>

             submitted <%=time_ago_in_words(post.created_at) %> ago by
             <%= post.user.name %> </br>
             <%= post.comments.count %> Coments
                 
             </small>

        </div>
      </div>

app/views/posts/edit.html.erb
<%= render partial: 'form', locals: { topic: @topic, post: @post} %>

app/views/posts/new.html.erb
<%= render partial: 'form', locals: { topic: @topic, post: @post} %>

app/views/posts/show.html.erb
<h1><%= markdown @post.title %></h1> 
     <div style="margin-top: 10px">
        <%= render partial: 'votes/voter', locals: { post: @post } %>
     </div>


<div class="row">
  <div class="col-md-8">
     <p><%= markdown @post.body %></p>
  </div>


  <div class="col-md-4">
    <%= link_to "Edit", edit_topic_post_path(@topic, @post), class: 'btn btn-success' %>
   <!-- nog even achterhalen wat hier nou het verschil is tussen de paden? -->
    
    <%= link_to "Delete post", [@topic, @post], method: :delete, class: 'btn btn-success', data: {confirm: "Are you sure?"} %>
    
    <div>  
      <h3> <%= pluralize(@post.points, 'point') %> <h3>
      <small>
         <%= pluralize(@post.up_votes, 'up vote') %>, 
         <%= pluralize(@post.down_votes, 'down vote') %>
       </small>  
    </div>

    <%= render partial: 'favorites/favorites', locals: { post: @post } %>

  </div>
</div>


    <div>

       
       <small>
         <%= pluralize(@post.up_votes, 'up vote') %>, 
         <%= pluralize(@post.down_votes, 'down vote') %>
       </small>
     

    
       <%= render @comments %>     


  </div>

<%= render partial: 'comments/form', locals: { topic: @topic, post: @post} %>

</div>